### ISSUE TITLE
The reviewers selected during the creation of the PR are not saved.

### ISSUE THREAD

**Issue by Gandhi11** [eXolnet/redmine_pulls#53]
**Describe the bug**
The reviewers selected during the creation of a PR are not saved.

**To Reproduce**
1. Go to 'Pull requests'
2. Click on 'New pull request'
3. Add informations and check some Reviewers.
3. Click on 'Create'
4. You should be redirected to the newly created PR and the Reviewers in the sidebar will be empty.

**Expected behavior**
In the newly created PR the Reviewers in the sidebar should be the one checked during the creation.

**Comment by xel1045** [comment]
Fixed
