### ISSUE TITLE
Redmine 4.1

### ISSUE THREAD

**Issue by ashrafalzyoud** [eXolnet/redmine_pulls#56]
Can u upgrade it?!

**Comment by xel1045** [comment]
Have you tried v1.2.0?

**Comment by ashrafalzyoud** [comment]
No such file to load -- redmine/scm/adapters/xitolite_adapter.rb (LoadError)

**Comment by ashrafalzyoud** [comment]
/home/redmine/4.1/plugins/redmine_pulls/lib/redmine_pulls/patches/adapters/xitolite_adapter_adapter.rb:1:in `<top (required)>'

**Comment by xel1045** [comment]
Can you copy the Redmine's "Information" page to show which version you have?

**Comment by ashrafalzyoud** [comment]
Redmine 4.1

**Comment by xel1045** [comment]
It should look like this:

![image](https://user-images.githubusercontent.com/1497697/91740682-a16ff900-eb81-11ea-933e-a3c12843796e.png)
